Dowload necessary libraries

In [ ]:
library(tidyverse)
library(ggmap)

Limit the number of rows and columns printed

In [ ]:
options(repr.matrix.max.rows=10, repr.matrix.max.cols=30) # for limiting the number of top and bottom rows of tables printed

Examine the data

In [ ]:
head(crime)

In [ ]:
str(crime)

Printing only the values of selected columns: time, offense, location

In [ ]:
crime %>%
select(time, offense, location)

Filtering to rows which hour is between 1 and 5, and the month is february

In [ ]:
crime %>% 
filter(between(hour, 1,5) & month == "february")

Creating a new column named time_hour which only shows the hour the crime is commited taken from the time column

In [ ]:
crime %>%
mutate(time_hour= substr(crime$time, 12,19)) %>%
mutate(time_hour_asnum = as.numeric(substr(time_hour, 1, 2)) + as.numeric(substr(time_hour, 4, 5)) / 60 + as.numeric(substr(time_hour, 7, 8)) / 3600) %>% 
mutate(end_time= time_hour_asnum + hour)

Printing the average hour of each offense group monthly

In [ ]:
crime %>%
group_by(offense, month) %>%
summarise (avg_hour= mean(hour),
           max_number = max(number))

In [ ]:
crimes_summary <- crime %>%
group_by(offense, month) %>%
summarise (avg_hour= mean(hour),
           max_number = max(number))

Showing average hour at a wide table grouped by months and offense

In [ ]:
crimes_summary_wide <- crimes_summary %>% pivot_wider(id_cols = month, names_from = offense, values_from = avg_hour)
crimes_summary_wide

Printing the crime_summary_wide table at a wide format

In [ ]:
crimes_summary_wide %>% 
pivot_longer(cols = -"month", names_to = "offense2", values_to = "avg_hour", values_drop_na = T)

Creating a new table to do left foint operation

In [ ]:
new_crime <- crime %>% select(time, offense, location, address)
new_crime

Joining table crime and new_crime on columns time and offense, the street and month columns are taken from crime table and location and address column are taken from new_crime table

In [ ]:
crime %>% select(time, offense,  street, month) %>% left_join(select(new_crime, offense, time, location, address), by = c("time" = "time", "offense"="offense"), relationship =
  "many-to-many")